pipeline {
    agent any
    options {
        skipDefaultCheckout()
    }
    stages {
        stage('Prepare') {
            steps {
                // Tests ?
                echo "Preparing"
                sh "printenv"
            }
        }
        stage('Deploy') {
            when {
                beforeAgent true
                expression { return env.TAG_NAME == "pws/deploy" }
            }
            agent { label 'eu-petro-ws' }
            steps {
                dir ("/home/www/petro.ws/blog") {
                    checkout scm
                }
            }
            post {
                cleanup {
                    deleteDir()
                }
            }
        }
    }
    post {
        cleanup {
            deleteDir()
        }
    }
}
