pipeline {
    agent { label 'eu-petro-ws' }
    options {
        skipDefaultCheckout()
        disableConcurrentBuilds()
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        stage('Prepare') {
            steps {
                // Tests ?
                echo "Preparing"
            }
        }
        stage('Deploy') {
            when {
                beforeAgent true
                expression { return env.TAG_NAME == "pws/deploy" }
            }
            steps {
                dir ("/home/www/petro.ws/blog/web") {
                    checkout scm
                }
            }
            post {
                cleanup {
                    deleteDir()
                }
            }
        }
    }
    post {
        cleanup {
            deleteDir()
        }
    }
}
