pipeline {
    agent { label 'eu-petro-ws' }
    stages {
        stage('Deploy') {
            steps {
                sh "echo 'Hello world!'"
            }
        }
    }
    post {
        cleanup { 
            deleteDir()
        }
    }
}
